/// Represents a single flight option in search results.
///
/// Core fields:
/// - id: Unique flight identifier
/// - airline/airlineLogo: Flight operator
/// - fromAirport/toAirport: Route endpoints (IATA codes)
/// - departureTime/arrivalTime: Scheduled times
/// - durationMinutes: Total travel time
/// - stops: Number of stops (0=direct, 1=1-stop, 2=2+ stops)
/// - cabinClass: Booking class (Economy, Business, etc.)
/// - price: Fare amount in display currency
/// - passengers: Passenger count for which price is calculated
///
/// Note: This is currently generated by mock [FlightService].
/// In production, integrate with live Schiphol API.
class Flight {
  const Flight({
    required this.id,
    required this.airline,
    required this.airlineLogo,
    required this.fromAirport,
    required this.toAirport,
    required this.departureTime,
    required this.arrivalTime,
    required this.durationMinutes,
    required this.stops,
    required this.layovers,
    required this.cabinClass,
    required this.price,
    this.passengers = 1,
  });

  final String id;
  final String airline;
  final String airlineLogo;
  final String fromAirport;
  final String toAirport;
  final DateTime departureTime;
  final DateTime arrivalTime;
  final int durationMinutes;
  final int stops;
  final List<String> layovers;
  final String cabinClass;
  final double price;
  final int passengers;

  static const Map<String, String> _preferredAirlineLogos = <String, String>{
    'Emirates': 'https://images.kiwi.com/airlines/64/EK.png',
    'Qatar Airways': 'https://images.kiwi.com/airlines/64/QR.png',
    'Turkish Airlines': 'https://images.kiwi.com/airlines/64/TK.png',
    'Etihad Airways': 'https://images.kiwi.com/airlines/64/EY.png',
    'PIA': 'https://images.kiwi.com/airlines/64/PK.png',
    'Pakistan International Airlines':
        'https://images.kiwi.com/airlines/64/PK.png',
  };

  static String preferredLogoForAirline(String airline) {
    return _preferredAirlineLogos[airline.trim()] ?? '';
  }

  static String sanitizeAirlineLogo({
    required String airline,
    required String airlineLogo,
  }) {
    final String preferred = preferredLogoForAirline(airline);
    final String trimmedLogo = airlineLogo.trim();

    if (trimmedLogo.isEmpty) {
      return preferred;
    }

    final Uri? uri = Uri.tryParse(trimmedLogo);
    if (uri == null) {
      return preferred.isNotEmpty ? preferred : trimmedLogo;
    }

    final String host = uri.host.toLowerCase();
    final bool isLegacyWikimedia =
        host == 'upload.wikimedia.org' || host.endsWith('.wikimedia.org');

    if (isLegacyWikimedia && preferred.isNotEmpty) {
      return preferred;
    }

    return trimmedLogo;
  }

  String get durationLabel {
    final int hours = durationMinutes ~/ 60;
    final int minutes = durationMinutes % 60;
    return '${hours}h ${minutes}m';
  }

  String get stopsLabel {
    if (stops == 0) {
      return 'Non-stop';
    }
    if (stops == 1) {
      return '1 stop';
    }
    return '$stops stops';
  }

  Map<String, dynamic> toMap() {
    return <String, dynamic>{
      'id': id,
      'airline': airline,
      'airlineLogo': airlineLogo,
      'fromAirport': fromAirport,
      'toAirport': toAirport,
      'departureTime': departureTime.millisecondsSinceEpoch,
      'arrivalTime': arrivalTime.millisecondsSinceEpoch,
      'durationMinutes': durationMinutes,
      'stops': stops,
      'layovers': layovers,
      'cabinClass': cabinClass,
      'price': price,
      'passengers': passengers,
    };
  }

  factory Flight.fromMap(Map<dynamic, dynamic> map) {
    final String airline = map['airline'] as String? ?? '';
    final String rawAirlineLogo = map['airlineLogo'] as String? ?? '';

    return Flight(
      id: map['id'] as String? ?? '',
      airline: airline,
      airlineLogo: sanitizeAirlineLogo(
        airline: airline,
        airlineLogo: rawAirlineLogo,
      ),
      fromAirport: map['fromAirport'] as String? ?? '',
      toAirport: map['toAirport'] as String? ?? '',
      departureTime: DateTime.fromMillisecondsSinceEpoch(
        (map['departureTime'] as int?) ?? 0,
      ),
      arrivalTime: DateTime.fromMillisecondsSinceEpoch(
        (map['arrivalTime'] as int?) ?? 0,
      ),
      durationMinutes: map['durationMinutes'] as int? ?? 0,
      stops: map['stops'] as int? ?? 0,
      layovers: ((map['layovers'] as List<dynamic>?) ?? <dynamic>[])
          .map((dynamic e) => e.toString())
          .toList(),
      cabinClass: map['cabinClass'] as String? ?? 'Economy',
      price: (map['price'] as num?)?.toDouble() ?? 0,
      passengers: ((map['passengers'] as num?)?.toInt() ?? 1).clamp(1, 9),
    );
  }
}



